name: "Run TODO to Issue"
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: "TODO to Issue"
      uses: "alstr/todo-to-issue-action@37bb7b56e58569ef273b60678048030a7f0c261a" # v5.1.15
